### ISSUE TITLE
Error to install proces

### ISSUE THREAD

**Issue by bellanz80** [CS-SI/qgis-contrast-homogenizer#4]
Hi, when installing the plug, I get an error window.

Windows 10 64 bit v.1903
QGIS 3.8.2
QGIS 3.4.11

Same error in two windows pc

Thank you very much for the help.
![Anotación 2019-09-02 110104](https://user-images.githubusercontent.com/38449926/64125909-56a28200-cd71-11e9-98e1-9c5253a74336.jpg)

**Comment by savmickael** [comment]
Hi, 
The plugin currently didn't not support QGIS 3. 
Moreover the project will be transfer to https://github.com/amondot/qgis-contrast-homogenizer in few moments and will be maintain via this repository. @amondot will open a tracker asap to foolow issue. Sorry you must re open your issue on this one.

**Comment by sdinot** [comment]
Hi @bellanz80,

Actually, CS SI doesn't maintain this plugin anymore. Therefore, this project is going to be archived in the next hours. @amondot has just taken over and she has forked it. Please see [amondot/contrast-homogenizer](https://github.com/amondot/contrast-homogenizer) and report your issue to @amondot.

Sorry for the inconvenience.

**Comment by bellanz80** [comment]
> Hi @bellanz80,
> 
> Actually, CS SI doesn't maintain this plugin anymore. Therefore, this project is going to be archived in the next hours. @amondot has just taken over and she has forked it. Please see [amondot/contrast-homogenizer](https://github.com/amondot/contrast-homogenizer) and report your issue to @amondot.
> 
> Sorry for the inconvenience.

Thank's!

**Comment by amondot** [comment]
A new version for this plugin will be released soon for QGIS3. You should install it via the plugin manager. Keep me informed if the bug is still here.
